config/routes.rb
PettyWarehousex::Engine.routes.draw do

  resources :items do
    collection do
      get :search
      get :search_results
      get :autocomplete
    end
  end
  
  root :to => 'items#index'
end

app/models/petty_warehousex/item.rb
module PettyWarehousex
  class Item < ActiveRecord::Base
    default_scope {where(fort_token: Thread.current[:fort_token])}
  
    attr_accessor :supplier_name, :received_by_name, :item_category_name, :warehouse_name, :project_name, :accepted_noupdate, :purchase_order_id_noupdate, 
                  :field_changed, :name_autocomplete, :item_sub_category_name, :whs_name, :i_unit_name, :part_name

    belongs_to :last_updated_by, :class_name => 'Authentify::User'
    belongs_to :received_by, :class_name => 'Authentify::User'
    belongs_to :item_category, :class_name => PettyWarehousex.category_class.to_s
    belongs_to :item_sub_category, :class_name => PettyWarehousex.sub_category_class.to_s
    belongs_to :supplier, :class_name => PettyWarehousex.supplier_class.to_s
    belongs_to :project, :class_name => PettyWarehousex.project_class.to_s
    belongs_to :purchase_order, :class_name => PettyWarehousex.purchase_order_class.to_s
    belongs_to :whs, :class_name => PettyWarehousex.whs_class.to_s
    belongs_to :i_unit, :class_name => 'Commonx::MiscDefinition'
    belongs_to :part, :class_name => PettyWarehousex.part_class.to_s

    validates :name, :unit, :storage_location, :in_date, :fort_token, :presence => true
    validates_numericality_of :in_qty, :greater_than_or_equal_to => 0
    validates :stock_qty, :numericality => {:greater_than_or_equal_to => 0, :less_than_or_equal_to => :in_qty}
    validates_numericality_of :project_id, :only_integer => true, :greater_than => 0, :if => 'project_id.present?'
    validates_numericality_of :whs_id, :only_integer => true, :greater_than => 0, :if => 'whs_id.present?'
    validates_numericality_of :purchase_order_id, :greater_than => 0, :if => 'purchase_order_id.present?'
    validates_numericality_of :total_cost, :greater_than => 0, :if => 'total_cost.present?'
    validates_numericality_of :unit_price, :greater_than => 0, :if => 'unit_price.present?'
    validates_numericality_of :item_category_id, :only_integer => true, :greater_than => 0, :if => 'item_category_id.present?'
    validates_numericality_of :item_sub_category_id, :only_integer => true, :greater_than => 0, :if => 'item_sub_category_id.present?'
    validates_numericality_of :supplier_id, :only_integer => true, :greater_than => 0, :if => 'supplier_id.present?'
    validates_numericality_of :i_unit_id, :only_integer => true, :greater_than => 0, :if => 'i_unit_id.present?'
    validates_numericality_of :part_id, :only_integer => true, :greater_than => 0, :if => 'part_id.present?'
    validate :dynamic_validate
    
    def dynamic_validate
      wf = Authentify::AuthentifyUtility.find_config_const('dynamic_validate', self.fort_token, 'petty_warehousex')
      eval(wf) if wf.present?
    end
  end
end

app/controllers/petty_warehousex/application_controller.rb
module PettyWarehousex
  class ApplicationController < ::ApplicationController
    include Authentify::SessionsHelper
    include Authentify::AuthentifyUtility
    include Authentify::UsersHelper
    include Authentify::UserPrivilegeHelper
    include Commonx::CommonxHelper
    include Searchx::SearchHelper
    
    before_action :require_signin
    before_action :max_pagination
    before_action :check_access_right 
    before_action :load_session_variable, :only => [:new, :edit]  #for parent_record_id & parent_resource in check_access_right
    after_action :delete_session_variable, :only => [:create, :update]  #for parent_record_id & parent_resource in check_access_right
    before_action :page_params, :only => :index
    
    helper_method :return_misc_definitions
    
    protected
  
    def max_pagination
      @max_pagination = find_config_const('pagination', session[:fort_token])
    end
    
  end
end

app/controllers/petty_warehousex/items_controller.rb
require_dependency "petty_warehousex/application_controller"

module PettyWarehousex
  class ItemsController < ApplicationController
    before_action :require_employee
    before_action :load_record
    after_action :info_logger, :except => [:new, :edit, :event_action_result, :wf_edit_result, :search_results, :stats_results, :acct_summary_result]
    
    def index
      @title = t('Warehouse Items')
      @items = params[:petty_warehousex_items][:model_ar_r]
      @items = @items.where(whs_string: @whs_string) if @whs_string
      @items = @items.where(whs_id: @whs_id) if @whs_id
      @items = @items.where(project_id: @project.id) if @project
      @items = @items.where(part_id: @part.id) if @part
      @items = @items.where(name: @part_name) if @part_name
      @items = @items.where(part_num: @part_num) if @part_num
      @items = @items.where(spec: @part_spec) if @part_spec
      @items = @items.page(params[:page]).per_page(@max_pagination)
      @erb_code = find_config_const('item_index_view', session[:fort_token], 'petty_warehousex')
      @js_erb_code = find_config_const('item_index_js_view', session[:fort_token], 'petty_warehousex')
    end
  
    def new
      @title = t('New Warehouse Item')
      @item = PettyWarehousex::Item.new()
      @item_category = return_misc_definitions('whs_item_category')
      @erb_code = find_config_const('item_new_view', session[:fort_token], 'petty_warehousex')
      @js_erb_code = find_config_const('item_new_js_view', session[:fort_token], 'petty_warehousex')
    end
  
    def create
      @item = PettyWarehousex::Item.new(new_params)
      @item.last_updated_by_id = session[:user_id]
      @item.received_by_id = session[:user_id]
      @item.stock_qty = params[:item][:in_qty]
      @item.fort_token = session[:fort_token]
      @item.whs_string = session[:whs_string] if session[:whs_string]
      if @item.save
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=Successfully Saved!")
      else
        #@whs_string = params[:item][:whs_string]
        @project = PettyWarehousex.project_class.find_by_id(params[:item][:project_id].to_i) if params[:item][:project_id].present?
        @item_category = return_misc_definitions('whs_item_category')
        @erb_code = find_config_const('item_new_view', session[:fort_token], 'petty_warehousex')
        @js_erb_code = find_config_const('item_new_js_view', session[:fort_token], 'petty_warehousex')
        flash[:notice] = t('Data Error. Not Saved!')
        render 'new'
      end
    end
  
    def edit
      @title = t('Update Warehouse Item')
      @item = PettyWarehousex::Item.find_by_id(params[:id])
      @item_category = return_misc_definitions('wh_item_category')
      @erb_code = find_config_const('item_edit_view', session[:fort_token], 'petty_warehousex')
      @js_erb_code = find_config_const('item_edit_js_view', session[:fort_token], 'petty_warehousex')       
    end
  
    def update
      @item = PettyWarehousex::Item.find_by_id(params[:id])
      @item.last_updated_by_id = session[:user_id]
      if @item.update_attributes(edit_params)
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=Successfully Updated!")
      else
        @item_category = return_misc_definitions('wh_item_category')
        @erb_code = find_config_const('item_edit_view', session[:fort_token], 'petty_warehousex')
        @js_erb_code = find_config_const('item_edit_js_view', session[:fort_token], 'petty_warehousex')  
        flash[:notice] = t('Data Error. Not Updated!')
        render 'edit'
      end
    end
  
    def show
      @title = t('Warehouse Item Info')
      @item = PettyWarehousex::Item.find_by_id(params[:id])
      @erb_code = find_config_const('item_show_view', session[:fort_token], 'petty_warehousex')
    end
    
    def destroy
      @item = PettyWarehousex::Item.find_by_id(params[:id])
      PettyWarehousex::Item.delete(params[:id].to_i)
      redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=Successfully Deleted!")
    end
    
    def autocomplete
      @items = PettyWarehousex::Item.where("stock_qty > ?", 0).order(:name).where("name like ?", "%#{params[:term]}%")
      render json: @items.map(&:name)    
    end  
    
    protected
    def load_record
      @whs_string = params[:whs_string].strip if params[:whs_string].present?
      @whs_string = session[:whs_string].strip if session[:whs_string].present?
      @whs_id = params[:whs_id].to_i if params[:whs_id].present?
      @whs_id = session[:whs_id].to_i if session[:whs_id].present? 
      qty_u = find_config_const('piece_unit', session[:fort_token])     
      @qty_unit = qty_u.split(',').map(&:strip) if qty_u.present? 
      qty_c = return_misc_definitions('piece_unit')
      @qty_unit ||= qty_c.pluck('name').join(',').split(',').map(&:strip) if qty_c.present?
      @project = PettyWarehousex.project_class.find_by_id(params[:project_id].to_i) if params[:project_id].present?
      item = PettyWarehousex::Item.find_by_id(params[:id]) if params[:id].present?
      @project = PettyWarehousex.project_class.find_by_id(item.project_id) if params[:id].present? && item.project_id.present?  #project_id optional
      #
      @part_name = params[:part_name] if params[:part_name]
      @part_num = params[:part_num] if params[:part_num]
      @part_spec = params[:part_spec] if params[:part_spec]
      @part = PettyWarehousex.part_class.find_by_id(params[:part_id].to_i) if params[:part_id]
    end
    
    private
    
    def new_params
      params.require(:item).permit(:in_date, :in_qty, :item_category_id, :last_updated_by_id, :name, :note, :other_cost, :spec, :stock_qty, :storage_location, :supplier_id, 
                    :unit, :unit_price, :inspection, :whs_string, :total_cost, :project_id, :accepted, :accepted_date, :purchase_order_id, :part_num, :aux_resource, :whs_id,
                    :part_id)
    end
    
    def edit_params
      params.require(:item).permit(:in_date, :in_qty, :item_category_id, :last_updated_by_id, :name, :note, :other_cost, :spec, :stock_qty, :storage_location, :supplier_id, 
                    :unit, :unit_price, :inspection, :whs_string, :total_cost, :accepted, :accepted_date, :purchase_order_id, :part_num, :part_id)
    end
  end
end

app/helpers/petty_warehousex/application_helper.rb
module PettyWarehousex
  module ApplicationHelper
  end
end

app/helpers/petty_warehousex/items_helper.rb
module PettyWarehousex
  module ItemsHelper
  end
end

app/views/petty_warehousex/items/_form.html.erb
<% if @erb_code %>
  <%= render inline: @erb_code %>
  
<% else %>
<h4><%=@title %></h4>
<%= simple_form_for @item do |f| %>    

  <%= f.input :name_autocomplete, :label => t("Item Name"), :input_html => { data: {autocomplete_source: base_materialx.autocomplete_parts_path}}, :readonly => readonly?(@item, 'name')%>
  <%= f.input :name %> 
  <%= f.input :field_changed, :as => :hidden %> 
  <%= f.input :spec, :label => t("Spec"), :readonly => true %>
  <%= f.input :in_date, :label => t("In Date"), :as => :string %> 
  <%= f.input :in_qty, :label => t("In Qty"), :readonly => readonly?(@item, 'in_qty') %>
  <%= f.input :unit, :label => t("Unit"), :readonly => true %> 
  <%= f.input :unit_price, :label => t("Unit Price($)"), :readonly => true, :input_html => {:value => @purchase_order.try(:unit_price)} %> 
  <%= f.input :other_cost, :label => t("Other Cost($))"), :readonly => readonly?(@item, 'other_cost') %>
  <%= f.input :total_cost, :label => t("Total Cost($)"), :readonly => readonly?(@item, 'total_cost') %>
  <%= f.input :storage_location, :label => t("Storage Location"), :readonly => readonly?(@item, 'storage_location') %> 
  <%= f.input :inspection, :label => t("Inspection"), :input_html => {:rows => 4}, :readonly => readonly?(@item, 'inspection') %> 
  <%= f.input :supplier_name, :label => t('Supplier'), :readonly => true, :input_html => {:value => @item.supplier.name} if readonly?(@item, 'supplier_id') %>
  <%= f.input :supplier_id, :label => t('Supplier'), :collection => PettyWarehousex.supplier_class.where(:active => true) unless readonly?(@item, 'supplier_id') %>
  <%= f.input :received_by_name, :label => t('Received By'), :readonly => true, :input_html => {:value => @item.received_by.name} %>
    
  <%= link_to t('Back'), SUBURI + "/view_handler?index=0", :class => BUTTONS_CLS['action'] %>
  <%= f.button :submit, t('Save'), :class => BUTTONS_CLS['action'] %>  
<% end %>

<% end %>

app/views/petty_warehousex/items/_form_list.html.erb
<% if  @erb_code %>
  <%= render inline: ERB.new(@erb_code).result(binding) %>
  
<% else %>
	
<div class="pagination"><%= will_paginate models %></div>
<h4><%=@title %></h4>
<p> <%= label_tag(:whs_name, t("Warehouse")) %>
	<%= select_tag(:whs_id, options_for_select(return_misc_definitions('warehouse').map{|r| [r.name, r.id]}), include_blank: true) %></p>
	<table class="table table-striped">
		<tr>
			<th>#</th>
			<th><%= t('In Date') %></th>
			<th><%= t('Item Name') %></th>
			<th><%= t('Spec') %></th>
			<th><%= t('In Qty') %></th>				
			<th><%= t('Stock Qty') %></th>
			<th><%= t('Warehouse') %></th>
			<th><%= t('Storage Location') %></th>			
			<th><%= t('Supplier') %></th>
			<th><%= t('Total Cost($)') %></th>
			<th><%= t('Received By') %></th>
			<th><%= t('Last Updated By') %></th>
			<th></th>
			<th></th>
			
		</tr>
		<% models.each do |r| %>
		  <tr>
		  	<% unless has_action_right?('show', params[:controller], r) %>
		  	  <td><%= prt(r, :id) %></td>
		  	<% else %>
		  	  <td><%= link_to r.id.to_s, SUBURI + "/view_handler?index=1&url=#{item_path(r)}" %></td>
		  	<% end %>
		  	<td><%= r.in_date.strftime("%Y/%m/%d") %></td>
		  	<td><%= prt(r, :name) %></td>
		  	<td><%= prt(r, :spec) %></td>
		  	<td><%= prt(r, :in_qty) %></td>
			<td><%= prt(r, :stock_qty) %></td>
			<td><%= prt(r, 'whs.name') if r.whs_id.present? %></td>
			<td><%= prt(r, :storage_location) %></td> 
			<td><%= prt(r,'supplier.name') %></td>
			<td><%= number_with_precision(r.total_cost, :precision => 2) if r.total_cost.present? %></td>
			<td><%= prt(r, 'received_by.name') %></td>
			<td><%= prt(r, 'last_updated_by.name') %></td>    
			<td><%= link_to t('Item Checkout'), SUBURI + "/view_handler?index=1&url=#{CGI::escape(item_checkoutx.checkouts_path(item_id: r.id))}", :class => BUTTONS_CLS['action']  if r.stock_qty > 0 && has_action_right?('index', 'item_checkoutx/checkouts', r) %></td>
			<td><%= link_to t('Edit'), SUBURI + "/view_handler?index=1&url=#{edit_item_path(r)}", :class => BUTTONS_CLS['action']  if has_action_right?('update', params[:controller], r) %></td>
		  </tr>
		<% end %>
	</table>
	
	<table class="table table-striped">
	  <tr>
	    <th>
	    	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	    	<%= link_to t('Back'), SUBURI + "/view_handler?index=0", :class => BUTTONS_CLS['action']  %>
	    	<%= link_to t('New Item'), SUBURI + "/view_handler?index=1&url=#{CGI::escape new_item_path(whs_string: @whs_string) }", :class => BUTTONS_CLS['action']  if @whs_string && has_action_right?('create', params[:controller]) %>
	    </th>
	  </tr>
	</table>
	

<% end %>	

app/views/petty_warehousex/items/_form_new.html.erb
<% if  @erb_code %>
  <%= render inline: @erb_code %>
  
<% else %>
<h4><%=@title %></h4>
<%= simple_form_for @item do |f| %>    

  <%= f.input :name_autocomplete, :label => t("Item Name"), :input_html => { data: {autocomplete_source: base_materialx.autocomplete_parts_path}},:placeholder => t("Enter Part Name Keyword"), :required => true  %>
  <%= f.input :name %> 
  <%= f.input :field_changed, :as => :hidden %> 
  <%= f.input :whs_string, :as => :hidden, :input_html => {:value => @whs_string}%>
  <%= f.input :spec, :label => t("Spec"), :readonly => true %>
  <%= f.input :in_date, :label => t("In Date"), :as => :string %> 
  <%= f.input :in_qty, :label => t("In Qty") %>
  <%= f.input :unit, :label => t("Unit"), :collection => @qty_unit, :include_blank => true %>  
  <%= f.input :unit_price, :label => t("Unit Price($)") %> 
  <%= f.input :other_cost, :label => t("Other Cost($)") %>
  <%= f.input :total_cost, :label => t("Total Cost($)") %>
  <%= f.input :storage_location, :label => t("Storage Location") %> 
  <%= f.input :inspection, :label => t("Inspection"), :input_html => {:rows => 4} %> 
  <%= f.input :supplier_id, :label => t('Supplier'), :collection => PettyWarehousex.supplier_class.where(:active => true), :include_blank => true %>
  <%= f.input :project_id, :label => t('Project#') %>
  <%= f.input :purchase_order_id, :label => t('PO#') %>
  <%= f.input :part_id, :as => :hidden %>
  
  <%= link_to t('Back'), SUBURI + "/view_handler?index=0", :class => BUTTONS_CLS['action'] %>
  <%= f.button :submit, t('Save'), :class => BUTTONS_CLS['action'] %>  
<% end %>

<% end %>

app/views/petty_warehousex/items/create.html.erb
<h1>Rfqs#create</h1>
<p>Find me in app/views/jobshop_rfqx/rfqs/create.html.erb</p>

app/views/petty_warehousex/items/edit.html.erb
<%= render 'form'  %>
 

  
 

app/views/petty_warehousex/items/edit.js.erb
<% if  @js_erb_code %>
  <%= render inline: ERB.new(@js_erb_code).result(binding) %>
  
<% else %>
  <% if params[:item][:field_changed] == 'item_name' && params[:item][:name_autocomplete] %>
    <% part = PettyWarehousex.material_item_class.find_by_name(params[:item][:name_autocomplete]) %>
    <% if part.present? %>
      $('#item_name').val("<%=part.name %>");
      $('#item_unit').val("<%=part.unit %>");
      <% if part.has_attribute?(:spec)%>
        $('#item_spec').val("<%=part.spec %>");
      <% elsif part.has_attributes?(:item_spec)%>
        $('#item_item_spec').val("<%=part.item_spec %>");
      <% end %>      
    <% else %>
      $('#item_name').val("");
      $('#item_spec').val("");
      $('#item_unit').val("");
    <% end %>
    $('#item_field_changed').val('');
  <% end %>
<% end %>

app/views/petty_warehousex/items/index.html.erb
<div id="index_page">

	<%= render partial: 'form_list', locals: {models: @items} %>

</div>

app/views/petty_warehousex/items/index.js.erb
<% if  @js_erb_code %>
  <%= render inline: ERB.new(@js_erb_code).result(binding) %>
  
<% else %>
<% if params[:field_changed] == 'whs_id'  %>
  <% @items = @items.where(whs_id: params[:whs_id].to_i) if params[:whs_id].present? %>
  $('#index_page').html("<%= escape_javascript render partial: 'form_list', locals: {models: @items, whs_id: params[:whs_id]} %>");
  $('#whs_id').val("<%=params[:whs_id]%>");
<% end %>

<% end %>

app/views/petty_warehousex/items/new.html.erb
<%= render 'form_new' %>

app/views/petty_warehousex/items/new.js.erb
<% if  @js_erb_code %>
  <%= render inline: ERB.new(@js_erb_code).result(binding) %>
  
<% else %>
  <% if params[:item][:field_changed] == 'item_name' && params[:item][:name_autocomplete] %>
    <% part = PettyWarehousex.material_item_class.find_by_name(params[:item][:name_autocomplete]) %>
    <% if part.present? %>
      $('#item_name').val("<%=part.name %>");
      $('#item_unit').val("<%=part.unit %>");
      <% if part.has_attribute?(:spec)%>
        $('#item_item_spec').val("<%=part.spec %>");
      <% elsif part.has_attributes?(:item_spec)%>
        $('#item_spec').val("<%=part.item_spec %>");
      <% end %>      
    <% else %>
      $('#item_name').val("");
      $('#item_spec').val("");
      $('#item_unit').val("");
    <% end %>
    $('#item_field_changed').val('');
  <% end %>
<% end %>

app/views/petty_warehousex/items/show.html.erb
<% if  @erb_code %>
  <%= render inline: ERB.new(@erb_code).result(binding) %>
  
<% else %>

<div class="container">
  <div class="page-header clearfix">
      <div class="pull-left">
        <h2><%=@title%></h2>
      </div>
    </div>
 <div class="row">
    <div class="col-sm-<%=BUTTONS_CLS['left-span#']%> form-group">
         <b><%= t('Warehouse') %></b>
    </div>
    <div class="col-sm-<%=BUTTONS_CLS['right-span#']%> form-group">
         <%= @item.whs.try('name')  %>
    </div>
 </div>
 <div class="row">
    <div class="col-sm-<%=BUTTONS_CLS['left-span#']%> form-group">
         <b><%= t('Item Name') %></b>
    </div>
    <div class="col-sm-<%=BUTTONS_CLS['right-span#']%> form-group">
         <%= @item.name %>
    </div>
 </div>
  <div class="row">
    <div class="col-sm-<%=BUTTONS_CLS['left-span#']%> form-group">
             <b><%= t('Spec') %></b>
    </div>
    <div class="col-sm-<%=BUTTONS_CLS['right-span#']%> form-group">
           <%= @item.spec %>
    </div>
 </div>
  <div class="row">
    <div class="col-sm-<%=BUTTONS_CLS['left-span#']%> form-group">
         <b><%= t('In Date') %></b>
    </div>
    <div class="col-sm-<%=BUTTONS_CLS['right-span#']%> form-group">
           <%= @item.in_date.strftime("%Y/%m/%d") if @item.in_date.present? %>
    </div>
 </div>
  <div class="row">
    <div class="col-sm-<%=BUTTONS_CLS['left-span#']%> form-group">
          <b><%= t('In Qty') %></b>
     </div>
    <div class="col-sm-<%=BUTTONS_CLS['right-span#']%> form-group">
            <%= @item.in_qty %>/<%= @item.i_unit.name if @item.i_unit_id.present? %>
    </div>
 </div> 
  <div class="row">
    <div class="col-sm-<%=BUTTONS_CLS['left-span#']%> form-group">
          <b><%= t('Stock Qty') %></b>
     </div>
    <div class="col-sm-<%=BUTTONS_CLS['right-span#']%> form-group">
            <%= @item.stock_qty %>/<%= @item.unit %>
    </div>
 </div>
 <div class="row">
    <div class="col-sm-<%=BUTTONS_CLS['left-span#']%> form-group">
          <b><%= t('Unit Price($)') %></b>
     </div>
    <div class="col-sm-<%=BUTTONS_CLS['right-span#']%> form-group">
            <%= number_with_precision(@item.unit_price, :precision => 2) if @item.unit_price.present? %>
    </div>
 </div>
  <div class="row">
    <div class="col-sm-<%=BUTTONS_CLS['left-span#']%> form-group">
          <b><%= t('Total Cost($)') %></b>
     </div>
    <div class="col-sm-<%=BUTTONS_CLS['right-span#']%> form-group">
            <%= number_with_precision(@item.total_cost, :precision => 2) if @item.total_cost.present? %>
    </div>
 </div>
  <div class="row">
    <div class="col-sm-<%=BUTTONS_CLS['left-span#']%> form-group">
          <b><%= t('Storage Location') %></b>
     </div>
    <div class="col-sm-<%=BUTTONS_CLS['right-span#']%> form-group">
            <%= @item.storage_location %>
    </div>
 </div>
  <div class="row">
    <div class="col-sm-<%=BUTTONS_CLS['left-span#']%> form-group">
           <b><%= t('Inspection') %></b>
    </div>
    <div class="col-sm-<%=BUTTONS_CLS['right-span#']%> form-group">
           <%= @item.inspection %>
    </div>
 </div>
 <div class="row">
    <div class="col-sm-<%=BUTTONS_CLS['left-span#']%> form-group">
           <b><%= t('Note') %></b>
    </div>
    <div class="col-sm-<%=BUTTONS_CLS['right-span#']%> form-group">
           <%= @item.note %>
    </div>
 </div>
  <div class="row">
    <div class="col-sm-<%=BUTTONS_CLS['left-span#']%> form-group">
           <b><%= t('Received By') %></b>
    </div>
    <div class="col-sm-<%=BUTTONS_CLS['right-span#']%> form-group">
           <%= @item.received_by.name %>
    </div>
 </div>
  <div class="row">
    <div class="col-sm-<%=BUTTONS_CLS['left-span#']%> form-group">
            <b><%= t('Last Updated By') %></b>
    </div>
    <div class="col-sm-<%=BUTTONS_CLS['right-span#']%> form-group">
            <%= @item.last_updated_by.name %>
    </div>
 </div>
   <div class="btn-toolbar">
     <%= link_to t('Back'), SUBURI + "/view_handler?index=0", :id => 'close', :class => BUTTONS_CLS['action'] %>
     <%= link_to t('New Log'), SUBURI + commonx.new_log_path(:resource_id => @item.id, :resource_name => params[:controller], :subaction => 'warehouse_item', :format => :js), :remote => true, 
                          :id => 'new_log_link', :class => BUTTONS_CLS['action'] if has_action_right?('create_warehouse_item', 'commonx/logs') %>
   </div>  
	
</div>
<% end %>

app/views/petty_warehousex/items/update.html.erb
<h1>Rfqs#update</h1>
<p>Find me in app/views/jobshop_rfqx/rfqs/update.html.erb</p>